SSD300:
  ratios: [[2],[2,3],[2,3],[2,3],[2],[2]]
  scales: [0.1,0.2,0.375,0.55,0.725,0.9,1.075]
  fm_sizes: [38,19,10,5,3,1]
  image_size: 300
  root_dir: '/mnt/sda2/lxl/code/ssd/dataset/VOCtrainval_06-Nov-2007/VOCdevkit/VOC2007'